externals/tremor: use own mirror
While updating Xiph's git repository URLs to their GitLab instance,
it turns out, that the moved Tremor repository misses commits:

error: Server does not allow request for unadvertised object
7c30a66346199f3f09017a09567c6c8a3a0eedc8
Fetched in submodule path 'externals/tremor', but it did not contain
7c30a66346199f3f09017a09567c6c8a3a0eedc8. Direct fetching of that commit
failed.

For more information see [0]!

0: https://gitlab.xiph.org/xiph/tremor/-/issues/2298